# Generated by Django 2.0.3 on 2018-04-27 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=250)),
                ('ngo_logo', models.CharField(max_length=1000)),
                ('ngo_loc', models.CharField(max_length=250)),
                ('ngo_relieftype', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ngodetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_details', models.CharField(max_length=3000)),
                ('ngo_address', models.CharField(max_length=100)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngo.Ngo')),
            ],
        ),
    ]
